# Generated by Django 5.1.2 on 2024-11-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euphoria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModelName',
            new_name='ImageUpload',
        ),
    ]
