# Generated by Django 5.1.2 on 2024-12-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euphoria', '0003_productload_textupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productload',
            name='name',
        ),
        migrations.AddField(
            model_name='productload',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
